---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zues865/public_html/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R user_guide $DEPLOYPATH
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp contributing.md $DEPLOYPATH
    - /bin/cp license.txt $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp readme.rst $DEPLOYPATH
    - /bin/cp .editorconfig $DEPLOYPATH
